# docker-compose.yml
version: '3.8'

networks:
  sauthml_net:
    driver: bridge

services:
  fastapi:
    image: sauthml-fastapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8007:8007"
    volumes:
      - .:/app
    networks:
      - sauthml_net